name: Docker Deploy Portfolio to VPS

on:
  push:
    branches: ["main"]
    paths-ignore:
      - ".github/workflows/**"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - ".github/workflows/**"

jobs:
  build-and-deploy:
    name: Build Docker & Deploy to VPS
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only deploy on main branch push

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: portfolio_frontend:latest
          outputs: type=docker,dest=/tmp/portfolio_frontend.tar

      - name: Copy Docker Image and Compose file to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.INPUT_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "/tmp/portfolio_frontend.tar,docker-compose.yml"
          target: "/home/wallydev-ops/apps/portfolio-frontend/"
          strip_components: 1 # Removes /tmp/ from the target path for the tar

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.INPUT_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Navigate to project directory
            mkdir -p /home/wallydev-ops/apps/portfolio-frontend
            cd /home/wallydev-ops/apps/portfolio-frontend

            # Load new image
            echo "Loading Docker image..."
            docker load -i portfolio_frontend.tar

            # Restart container
            echo "Restarting service..."
            docker compose down
            docker compose up -d


            # Cleanup files
            rm portfolio_frontend.tar

            # Prune dangling images (prevents disk fill-up)
            docker image prune -f

            echo "Deployment successful!"
