name: vite-deploy to VPS - CI/CD

on:
  push:
    branches: ["main"]
    paths-ignore:
      - ".github/workflows/**"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - ".github/workflows/**"

jobs:
  build:
    name: Build for Production
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: |
            ./dist
            ./package.json

  deploy:
    name: Deploy on VPS
    needs: build
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: .

      - name: Copy production files to public_html
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USER}}
          password: ${{secrets.INPUT_PASSWORD}}
          port: ${{secrets.SSH_PORT}}
          source: "./dist/*,./package.json"
          target: "/home/wallydev-ops/web/wallydev.dev/public_html/"
          overwrite: true

      - name: Copy files from Dist to public_html
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USER}}
          password: ${{secrets.INPUT_PASSWORD}}
          port: ${{secrets.SSH_PORT}}
          script: cp -r /home/wallydev-ops/web/wallydev.dev/public_html/dist/* /home/wallydev-ops/web/wallydev.dev/public_html

      - name: Execute
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USER}}
          password: ${{secrets.INPUT_PASSWORD}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd /home/wallydev-ops/web/wallydev.dev/public_html
            source /home/wallydev-ops/.nvm/nvm.sh  # Cargar NVM
            nvm use v20.13.1  # Establecer la versiÃ³n de Node.js
            /home/wallydev-ops/.nvm/versions/node/v20.13.1/bin/npm install --omit=dev
            nohup /home/wallydev-ops/.nvm/versions/node/v20.13.1/bin/npm run preview --port 3000 > nohup.out 2>&1 &
            sleep 5  # Asegurarse de que el comando nohup se ejecute correctamente

      - name: Track Deployed Port
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USER}}
          password: ${{secrets.INPUT_PASSWORD}}
          port: ${{secrets.SSH_PORT}}
          script: |
            echo "Finding deployed port..."
            sleep 2  # A small delay to ensure the app has started
            PORT=$(lsof -i -P -n | grep LISTEN | grep node | awk '{print $9}' | cut -d':' -f2)
            echo "Application is running on port: $PORT"
            echo "Application is running on port: $PORT" > /home/wallydev-ops/web/wallydev.dev/public_html/deployed_port.txt

  debug_ip:
    name: Debug IP Address
    runs-on: ubuntu-latest
    needs: deploy
    if: always()

    steps:
      - name: Debug IP
        run: |
          curl ifconfig.me
